language: java

# http/settings.gradle Added here to enable http subproject to be built without the root project
install:
  - touch http/settings.gradle
  - cd http; ../gradlew assemble; cd ..
script:
  - cd http && ../gradlew check && cd ..

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper

after_success:
  - bash <(curl -s https://codecov.io/bash)